server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

logging:
  level:
    com.enterprise.meeting: WARN
    org.springframework.security: WARN
